# -*- coding: utf-8 -*-
"""LVADSUSR102_prabu_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oDsbGfezOUNtDr0KLjCqlp4i3BnVU3Dk
"""

#1 Random Forest Classfication
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error,accuracy_score, precision_score, recall_score

# 1. read the data
data = pd.read_csv('/content/drive/MyDrive/loan_approval.csv')

# EDA

print("---------------Exploratory Data Analysis------------------")
print(data.describe())
print("------------")
print(data.info())
print("------------")
print(data.head())

# 2 a. Handling missing values with mean
data.fillna(data.mean(), inplace=True)

# Handling duplicates
data.drop_duplicates(inplace=True)

# Encoding categorical to numerical
label_encoder=LabelEncoder()
data[' education']=label_encoder.fit_transform(data[' education'])
data[' self_employed']=label_encoder.fit_transform(data[' self_employed'])


# Split features and labels
features = data.drop([' loan_status'], axis=1)

# 2 b.Plotting boxplots before managing outliers
plt.figure(figsize=(9, 5))
sns.boxplot(data=features)
plt.title("Before managing Outliers")
plt.ylabel('Values')
plt.xticks(rotation=45)
plt.show()

# 2 b.Function to manage outliers
def manage_outliers(data, columns):
    for col in columns:
        Q1 = data[col].quantile(0.25)
        Q3 = data[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        median = data[col].median()
        data[col] = np.where((data[col] < lower_bound) | (data[col] > upper_bound), median, data[col])
    return data

# 2b. Manage outliers
features = manage_outliers(features, features.columns)

# 2 b. Plotting boxplots after managing outliers
plt.figure(figsize=(9, 5))
sns.boxplot(data=features)
plt.title("After managing Outliers")
plt.ylabel('Values')
plt.xticks(rotation=45)
plt.show()

#4. Model Training and testing

labels=label_encoder.fit_transform(data[' loan_status'])
# Assigning Test and Training variables
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3, random_state=42)

# Execute Random Forest Classification
clf = RandomForestClassifier()
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)

# Print predicted values
print("-------------------Predictions--------------------")
print(predictions)

#5. Evaluation metrices

print("------------------Evaluation matrices------------")
r2 = r2_score(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))
accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')


# Print the performance metrics
print('Accuracy:', accuracy)
print('Precision:', precision)
print('Recall:', recall)